services:
  service:
    image: service
    build:
      context: .
      dockerfile: Service/Dockerfile

  dataaccess:
    image: dataaccess
    build:
      context: .
      dockerfile: DataAccess/Dockerfile
